apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:M0I9cCJEFFz0vkRuUl465AIzY9Hy6Pw2KZXjPvQABHUB64BTZRQjAo/KYw98iAfH3BHsrgHjYl8juC26aPL+5qlbTvp0ILa9UDWbhXGlpOgrG+e8XegqFJCilc2A2Zayh6RLiEWF5tW0rsOD/nAmkfvBj4+G19rO7JYcgOjvJNyA5DA/bEkOxGmtA9ee8Sa3jsYgEIUUEXV+g5+GPsCgQJTWEHFErDPBmn10R+3k9heOD1YpGE2Iui8LOlGCdRPh7pjwyx0yAQE0edKngQ43t61lklpi1pVbCLpGXadGjgGpTEs3o8rK3pdMfy0=,iv:vjfLXZyC8NAWRF2tQAfSMzqN3X+/wjeIQkCnSV6JgR4=,tag:vRK3yzlEiX81+haDWWrK/A==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: audiobookshelf
sops:
    age:
        - recipient: age1j3rlxn82m68mzf5sd8ujgkhplcukslsxkl2yjxehxjwdyx5x8czq6289cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVUcwRldSM3lKTE5oKzE2
            MUtLMGhCR1FXRU9KbEpZSmRiNG5CNzV5RjBnCnpidzQxMi9XZWlxNGpuS3hldVBY
            WGJ6RXg2akQ0MDVrZXpScHlLbEwydlkKLS0tIDBHVGt6MyttdlJnMld6MU0wS054
            MWZ2VHVJVHZXU1lxalE3QnMzYkNHYlkKHL71jeJe12/EcYH3sxvO1hWC408cOCnO
            2fz1/yX1FyZWXqLGJC9SU8WXS73mIIVOCfF+yD8RWk3MB6mF6ImZSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T10:15:38Z"
    mac: ENC[AES256_GCM,data:WX9/ewojHb+G8hJ8fW5ix6rP9F8Vwe0PW9Mf8aEEsmplYmttbfhRfJF800l+S9mHknUA7xMMTOtjz7N6lCuJ7XmYZTkIoe/EMBrl7ptjamZjltqymSk5vBmeQA4PDCD2TgByGkj8gkINZNHdTGTqie64DCUP8B1p/7D6Xstd20M=,iv:X4HeOE3sLi7XdxGTXyzsEJpKMJiBbm3e9SjbMKaU4Io=,tag:hCsXc8cTJDbtyA6etsMk8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
