apiVersion: v1
data:
    password: ENC[AES256_GCM,data:VBVhzAJ6ZnU=,iv:OJy8/zQcWsd7UfXFCsScGDv8DkBPgLBQtZoCug4IfUk=,tag:n9MihMFmj//Dk1YXhtb5Bg==,type:str]
    user: ENC[AES256_GCM,data:QSaZqTd46Ys=,iv:ehtSrUZwenid64Ub5M98MhjrcIJzYFNeWzihOX3XkOI=,tag:9+aXLIhDs03SSvcekWiCug==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1j3rlxn82m68mzf5sd8ujgkhplcukslsxkl2yjxehxjwdyx5x8czq6289cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbDNYc1RCcXdJN2x3alBz
            ZlUralpRR1hGdzFMaWFiLytqK0dQVlBoODJjCk9FWlVBUFUxcVVQK1dOem1qc0Nr
            dG1zTHpqeGlZWVN6RFlDeGZoaEVUTlUKLS0tIDAwTkg2UG82dW93VHBOK0d3TEFj
            enE3cVRFVnU4OEJMWGxKQWtFY3A5bDQK8Syzcxs0xPryD2sIvHUr+3zqQS5FyieR
            PG3Zp4aa3iDYWdGBS7SKwkwzgCGPcZMq3YPwJ76GO76v+X8pBDhINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T18:21:45Z"
    mac: ENC[AES256_GCM,data:IW7627cxGOVSpvSWPZOjpObC8WKSrftBQvA4FJIau8mswOYO/jL6DTg2mqdnt2touMGqWs0NHbOpsPpvQOMv6ntexG0IlLyxCKvNHL9toYGB7Wmuc2BGMv3eC/CJZ4ziNzJ4HEZXyAkbOjDc/KBPOR5kNqqvyNY6k7EFlQu6OIc=,iv:gaJavg1Yldupk6tywx6JjRlHyh4+eL0Y8/bfc1GbWHc=,tag:smhKhzAAKGaORFvAY+sYKA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
