apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:MXS+UrYLkI/cziK6VvKtRVPvinrpRfH8t+vGLuShzxpgKm9w0qbMztOc70JM04C9uqOHiIcEVpBj9rp+x+bxsLCTs4Alivu3VuPA8EpzCWmU6EZTKlLfhscz0yZ2Za2jou8NzoXfPA6bMDAsx/+gZw84YexJqGHujPUdqPh57kzPAjIJRtlwS/q/V8vd+nqedYcfmKLVw79j2s8zeVY+3dBhQNx4nMfmmrMKV8fk2Wi/vxXKqAILFkmDdvCJSr2p+CRVK/KDD7H5p+DtzuLjG6C410h8ZIC1W4vGDmTeGG8yaCCPwsHLjGSRdP4=,iv:J72WQevq7+2gRDA2SJD1NrH3t2i0q/cmCWJ0LmBlmSY=,tag:HalwWed4vKZZJY/lubl6eg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    age:
        - recipient: age1j3rlxn82m68mzf5sd8ujgkhplcukslsxkl2yjxehxjwdyx5x8czq6289cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTc2NZVDZzMzRUeEZEWUc2
            dFd5K2FWYmhGcmdtcnloNE1WVjRRTE5aUmlVCms4bTYvclIwUXkxSTE1M3RGSEZR
            TndmbURrNDJibVlTd0VjUzQyZk1nZW8KLS0tIFVmb1J6YVcwMW9ybncyd3FtQlM3
            QVRiTThkL3ROQTBrdWZPd2VSN21EaDQKUw86BNMbVcdpWPaO48//4xazijpFDJ5V
            aw9DTPJDlt1ZAy2pTmrmRvywKPim+Cxw4jUt0DGZBCPKwye+NwtdGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T18:59:35Z"
    mac: ENC[AES256_GCM,data:0L/GWtaH4X9xAwm4yKyuZA7ZKYm6Vu+mvVHPLKZ01e5hn89RN7+QrIcK0xvg+qNgVis8yMO1c1JmuHzR/CzPMRjQUHxV57kRwOI/s6sqCvk/aEDTDtUsqzVouevC+2BlcklpqsjdFtDs0+vUaQhiP/7sdz00PDfuSUdqvJWeYAM=,iv:U5rfw88uNviq9dUn0J4+NcYqwbVp8zFkrTPZ6s7DiD8=,tag:ng9BfqRXsfsTWmfwLOB6Kg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
